package com.constellation.glass.app.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.BasicText
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.constellation.glass.hud.HudTheme

/**
 * First-launch / re-pair login. **Scan-only** (Zack 2026-05-31): the eyewear
 * never types a password — auth + endpoint both come from the pairing QR
 * generated by the web console's About/Pair page (which is where the password
 * actually lives). One button: SCAN QR.
 *
 * Once paired, the app NEVER shows this again (no logout — cookie permanent).
 */
@Composable
fun LoginScreen(
    endpoint: String,
    status: String = "Scan the pairing QR from your web console (About / Pair).",
    onScanQr: () -> Unit = {},
) {
    Column(
        Modifier
            .fillMaxSize()
            .background(Color.Black)
            .padding(horizontal = ScreenPadding, vertical = 24.dp),
    ) {
        BasicText(
            text = "Constellation",
            style = TextStyle(
                fontSize = HudTheme.titleSize,
                fontWeight = FontWeight.Bold,
                color = HudTheme.fg,
            ),
        )
        Spacer(Modifier.height(6.dp))
        BasicText(
            text = endpoint.ifBlank { "not paired yet" },
            style = TextStyle(
                fontSize = HudTheme.footerSize,
                fontFamily = FontFamily.Monospace,
                color = HudTheme.fgDim,
            ),
        )

        Spacer(Modifier.height(24.dp))

        BasicText(
            text = status,
            style = TextStyle(fontSize = HudTheme.bodySize, color = HudTheme.fg),
        )

        Spacer(Modifier.height(20.dp))

        Cta(text = "SCAN QR", onClick = onScanQr)
    }
}

@Preview(name = "Login — scan only", widthDp = 480, heightDp = 640, backgroundColor = 0xFF000000, showBackground = true)
@Composable
private fun PreviewLogin() {
    LoginScreen(endpoint = "wss://edge.example.com/ws/glass")
}
